version: '3.8'

services:
  traefik:
    image: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  static_server_a:
    image: mynginx
    build: ../StaticWebServer
    expose:
      - "80"
    volumes:
      - ./../DockerCompose/site-a:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static_server_a.rule=Host(`site-a.localhost`)"
    deploy:
      replicas: 3

  static_server_b:
    image: mynginx
    expose:
      - "80"
    volumes:
      - ./../DockerCompose/site-b:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static_server_b.rule=Host(`site-b.localhost`)"
    deploy:
      replicas: 3



  api_server:
    build: ./../HTTP_API_Server
    expose:
      - "7002"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api_server.rule=Host(`localhost`) && PathPrefix(`/api`)"
    deploy:
      replicas: 3