//exemple des slides (à effacer)


version: '3.8'
services:
loadbalancer:
image: traefik:v2.5
ports:
- "80:80"
webserver:
image: heigvd/mywebserver
environment:
DBSERVER: database
deploy:
replicas: 5
database:
image: mysql:8.0
environment:
MYSQL_ROOT_PASSWORD: example_password